export const AD_PATTERNS: string[] = [
  "*://*.doubleclick.net/*",
  "*://*.googlesyndication.com/*",
  "*://*.googleadservices.com/*",
  "*://*.googletagservices.com/*",
  "*://*.googletagmanager.com/*",
  "*://*.google-analytics.com/*",
  "*://*.amazon-adsystem.com/*",
  "*://*.ads.yahoo.com/*",
  "*://*.advertising.com/*",
  "*://*.adsrvr.org/*",
  "*://*.criteo.com/*",
  "*://*.criteo.net/*",
  "*://*.outbrain.com/*",
  "*://*.taboola.com/*",
  "*://*.revcontent.com/*",
  "*://*.mgid.com/*",
  "*://*.popads.net/*",
  "*://*.popcash.net/*",
  "*://*.adnxs.com/*",
  "*://*.rubiconproject.com/*",
  "*://*.pubmatic.com/*",
  "*://*.openx.net/*",
  "*://*.smartadserver.com/*",
  "*://*.adform.net/*",
  "*://*.ads-twitter.com/*",
  "*://*.facebook.net/*",
  "*://*.fbcdn.net/*",
  "*://*.moatads.com/*",
  "*://*.scorecardresearch.com/*",
  "*://*.quantserve.com/*",
  "*://*.hotjar.com/*",
  "*://*.crazyegg.com/*",
  "*://*.fullstory.com/*",
  "*://*.mixpanel.com/*",
  "*://*.segment.io/*",
  "*://*.amplitude.com/*",
  "*://*.newrelic.com/*",
  "*://*.nr-data.net/*",
  "*://*.pingdom.net/*",
  "*://*.chartbeat.com/*",
  "*://*.parsely.com/*",
  "*://*.innovid.com/*",
  "*://*.spotxchange.com/*",
  "*://*.freewheel.tv/*",
  "*://*.jwpltx.com/*",
  "*://*.adsymptotic.com/*",
  "*://*.mathtag.com/*",
  "*://*.bidswitch.net/*",
  "*://*.contextweb.com/*",
  "*://*.lijit.com/*",
  "*://*.sovrn.com/*",
  "*://*.media.net/*",
  "*://*.lijit.com/*",
  "*://*.zergnet.com/*",
  "*://*.sharethrough.com/*",
  "*://*.triplelift.com/*",
  "*://*.indexww.com/*",
  "*://*.casalemedia.com/*",
  "*://*.simpli.fi/*",
  "*://*.crwdcntrl.net/*",
  "*://*.demdex.net/*",
  "*://*.agkn.com/*",
  "*://*.rlcdn.com/*",
  "*://*.bluekai.com/*",
  "*://*.eyeota.net/*",
  "*://*.exelator.com/*",
  "*://*.rfp.io/*",
  "*://*.stickyadstv.com/*",
  "*://*.teads.tv/*",
  "*://*.undertone.com/*",
  "*://*.coxmt.com/*",
  "*://*.betweendigital.com/*",
  "*://*.addthis.com/*",
  "*://*.sharethis.com/*",
  "*://*.outbrainimg.com/*",
  "*://*.taboolasyndication.com/*",
  "*://*.adblade.com/*",
  "*://*.nativo.com/*",
  "*://*.powerlinks.com/*",
  "*://*.yahooapis.com/*",
  "*://*.ads.*",
  "*://*.ad.*",
  "*://*.banner*",
  "*://*.popup*",
  "*://*.sponsor*",
  "*/ads/*",
  "*/adserver/*",
  "*/banner/*",
  "*/sponsored/*",
  "*/popunder/*",
  "*/popup/*",
];

export function matchesAdPattern(url: string): boolean {
  const lower = url.toLowerCase();
  for (const pattern of AD_PATTERNS) {
    const stripped = pattern
      .replace(/^\*\:\/\//, "")
      .replace(/^\*\./, "")
      .replace(/\*/g, "");
    if (stripped && lower.includes(stripped)) {
      return true;
    }
  }
  return false;
}
